module.exports = {
  testUrl: "https://robyn.recipes/vegetarian/2019/10/17/potato-leek-soup/",
  invalidUrl: "https://robyn.recipes/notarealurl",
  invalidDomainUrl: "www.invalid.com",
  nonRecipeUrl: "https://robyn.recipes/about/",
  expectedRecipe: {
    name: "Potato Leek Soup",
    ingredients: [
      "1 pound leeks, cleaned and dark green sections removed, approximately 4 to 5 medium",
      "3 tablespoons unsalted butter",
      "Heavy pinch kosher salt, plus additional for seasoning",
      "5 yukon gold potatoes, peeled and diced small",
      "1 quart vegetable broth/stock (or chicken broth)",
      "1 cup heavy cream",
      "1 - 1 1/2 cups buttermilk",
      "1/2 teaspoon white pepper",
      "1 tablespoon snipped chives",
    ],
    instructions: [
      "Chop the leeks into small pieces. Rinse any lingering dirt off of the leeks that appears while chopping them; I throw them in a colander and toss them around under running water.",
      "In a 6-quart saucepan over medium heat, melt the butter. Add the leeks and a heavy pinch of salt and sweat for 5 minutes. Decrease the heat to medium-low and cook until the leeks are tender, approximately 25 minutes, stirring occasionally.",
      "Add the potatoes and the vegetable broth, increase the heat to medium-high, and bring to a boil. Reduce the heat to low, cover, and gently simmer until the potatoes are soft, approximately 45 minutes.",
      "Turn off the heat and puree the mixture with an immersion blender until smooth. 5. Stir in the heavy cream, buttermilk, and white pepper. Taste and adjust seasoning if desired. Sprinkle with chives and serve immediately, or chill and serve cold.",
    ],
    tags: [],
    time: {
      prep: "25 minutes",
      cook: "1 hour 15 minutes",
      active: "",
      inactive: "",
      ready: "",
      total: "",
    },
    servings: "6",
    image: "https://robyn.recipes/images/potatoLeekPortrait.jpg",
  },
};
